#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
#---------------------------------------------------#
# -----------!!!!!!!!!!!!!!!!!混合端口 HTTP和SOCKS5用一个端口!!!!!!!!!!!!!!!!
mixed-port: 7890

# HTTP 代理端口
# port: 7890

# SOCKS5 代理端口
#socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 透明代理端口 Transparent proxy server port (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# 允许局域网的连接（可用来共享代理）----false true
allow-lan: false

# -----仅在将allow-lan设置为true时适用----------
# #"*": 绑定所有IP地址
# #192.168.122.11: 绑定单个IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"
ipv6: false

# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: warning

# Clash 的 RESTful API
#external-controller: '127.0.0.1:9090'

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# http://127.0.0.1:9090/ui/#/
# external-ui: folder
# yacd面板：  https://github.com/haishanh/yacd
# Razord面板：http://clash.razord.top/#/proxies
# external-ui: dashboard

# RESTful API 的口令 (可选)
# secret: ""

# 实验性功能
#experimental:
#  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true
  # interface-name: en0 # outbound interface name

# 本地 SOCKS5 / HTTP(S) 服务认证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效
#hosts:
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'
hosts:
   'api.dler.io': 172.67.203.47
   'api.wcc.best': 172.67.140.28
   'sub.789.st': 172.67.193.176
   'subconverter.herokuapp.com': 54.165.58.209
   'sub.id9.cc': 104.218.235.103
   'raw.githubusercontent.com': 185.199.108.133
   'uuu.glass': 45.88.195.157
   'ftp.xhrzg2017.xyz': 172.16.0.5
   'www.xhrzg2017.xyz': 172.16.0.4
   
#profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  #store-selected: false

  # persistence fakeip
  #store-fake-ip: true
#dns:
  #enable: true # 是否启用dns false
  #ipv6: false
  #listen: 0.0.0.0:53
  #enhanced-mode: redir-host # 模式：redir-host或fake-ip
  #fake-ip-range: 198.18.0.1/16 #
  #fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
     #- '*.lan'
     #- localhost.ptlogin2.qq.com
  #nameserver:
     #- 223.5.5.5 # 阿里DNS
     #- 180.76.76.76 # 百度DNS
     #- 119.29.29.29 # 腾讯DNS
     #- 117.50.11.11 # ONE DNS拦截版 恶意网站拦截、广告过滤
     #- 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
     #- 114.114.114.114 # 114DNS
     #- https://dns.alidns.com/dns-query # 阿里 DoH DNS
     #- https://doh.360.cn/dns-query # 360 DoH DNS
  #fallback:
     #- 8.8.8.8 # 谷歌DNS
     #- 1.1.1.1 # Cloudflare DNS
     #- tls://dns.rubyfish.cn:853
     #- tls://1.0.0.1:853
     #- tls://dns.google:853
     #- https://dns.rubyfish.cn/dns-query
     #- https://cloudflare-dns.com/dns-query
     #- https://dns.google/dns-query
  #fallback-filter:
     #geoip: true # 默认
     #ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
       #- 240.0.0.0/4
clash-for-android:
  append-system-dns: false
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:  
    # === LAN ===
    - '+.lan'
    - '*.lan'
    # === Windows 10 Connnect Detection ===
    - '*.ipv6.microsoft.com'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'msftconnecttest.com'
    - 'msftncsi.com'
    - '+.msftnsci.com'
    - '+.msftconnecttest.com'
    # === NTP Service ===
    - 'ntp.*.com'
    - time-ios.apple.com
    - time-macos.apple.com
    - 'time.*.com'
    - 'time.*.gov'
    - '+.pool.ntp.org'
    - '*.cloud.tencent.com'
    - '*.pool.ntp.org'
    - pool.ntp.org
    ## === 国内网站 ===
    - '+.baidu.com'
    - '*.alipay.com'
    - '*.alipayobjects.com'
    - '*.163.com'
    - '*.126.net'
    - '*.taihe.com'
    - '*.kugou.com'
    - '*.joox.com'
    - joox.com
    - '*.*.*.*.qq.com'
    - '*.*.*.qq.com'
    - '*.*.qq.com'
    - '*.qq.com'
    - '*.*.*.*.*.cn'
    - '*.*.*.*.cn'
    - '*.*.*.cn'
    - '*.*.cn'
    - '*.cn'
    - '+.cn'
    # === Apple Software Update Service ===
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    # === Game Service ===
    - "*.battle.net"
    ## Microsoft Xbox
    - 'speedtest.cros.wr.pvp.net'
    - '*.*.xboxlive.com'
    - 'xbox.*.*.microsoft.com'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    ## Nintendo Switch
    - '*.*.*.srv.nintendo.net'
    - '+.srv.nintendo.net'
    ## Sony PlayStation
    - '*.*.stun.playstation.net'
    ## STUN Server
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*'
    - 'stun.*.*.*'
    - 'stun.*.*'
    
  nameserver:
  - 'https://doh.pub/dns-query'
  - 'https://dns.alidns.com/dns-query'

  fallback:
    # -国内可用的 doh、dot 列表
    - 'https://doh.xhrzg2017.xyz/low'
    - 'https://dns.google/dns-query'
    - 'https://doh.dns.sb/dns-query'
    - 'https://rubyfish.cn/dns-query'

    
    #- 'https://public.dns.iij.jp/dns-query'
    #- 'https://doh.opendns.com/dns-query'
    #- 'https://doh.dns.sb/dns-query'
    #- 'https://101.101.101.101/dns-query'
    #- 'https://a.passcloud.xyz/hk'
    #- 'https://1.0.0.1/dns-query'
    #- 'https://azure.cloudflare-dns.com/dns-query'
    #- 'https://dns.switch.ch/dns-query'
    #- 'tls://8.8.4.4'
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
#      - 0.0.0.0/32
      - 127.0.0.0/8
      - 0.0.0.0/8
#      - 10.0.0.0/8
      - 100.64.0.0/10
      - 169.254.0.0/16
#      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
#      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 255.255.255.255/32
    domain:
      # 设置这3个有必要吗
      # - '+.facebook.com'
      # - '+.twitter.com'
      # - '+.youtube.com'
      # google cn
      - '+.xn--ngstr-lra8j.com'
      - 'www.gstatic.cn'
      - '+.google.cn'
      - '+.googleapis.cn'
      - '+.gvt1.com'
      # google 服务
      - 'translate.googleapis.com'
      - 'safebrowsing-cache.google.com'
      - 'safebrowsing.googleapis.com'
      - 'clientservices.googleapis.com'
      # 微软网站      
      - '+.bing.com'
      - '+.linkedin.com'
      - '+.msn.cn'
      # apple tv      
      - 'www.apple.com'
      - 'tv.apple.com'
      #- 'np-edge.itunes.apple.com'
      #- 'play-edge.itunes.apple.com'
      # sony playstation     
      - '+.playstationnetwork.com'
      - '+.sony.com'
      - '+.sonyentertainmentnetwork.com'
      - '+.playstation.com'
      #- '+.playstation.net'
      # App Store
      - '+.mzstatic.com'
      - 'itunes.apple.com'
      - '+.itunes.apple.com'
      - '+.phobos.apple.com'
      - '+.aaplimg.com'
      - 'apps.apple.com'
#  Apple TV https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleTV.list
#cfw tun mode配置
#失效
# 1. clash DNS 请求逻辑：
#   (1) 当访问一个域名时， nameserver 与 fallback 列表内的所有服务器并发请求，得到域名对应的 IP 地址。
#   (2) clash 将选取 nameserver 列表内，解析最快的结果。
#   (3) 若解析结果中，IP 地址属于 国外，那么 clash 将选择 fallback 列表内，解析最快的结果。
#
#   因此，我在 nameserver 和 fallback 内都放置了无污染、解析速度较快的国内 DNS 服务器，以达到最快的解析速度。
#   但是 fallback 列表内服务器会用在解析境外网站，为了结果绝对无污染，我仅保留了支持 DoT/DoH 的两个服务器。
#
# 2. clash DNS 配置注意事项：
#   (1) 如果您为了确保 DNS 解析结果无污染，请仅保留列表内以 tls:// 或 https:// 开头的 DNS 服务器，但是通常对于国内域名没有必要。
#   (2) 如果您不在乎可能解析到污染的结果，更加追求速度。请将 nameserver 列表的服务器插入至 fallback 列表内，并移除重复项。
#
# 3. 关于 DNS over HTTPS (DoH) 和 DNS over TLS (DoT) 的选择：
#   对于两项技术双方各执一词，而且会无休止的争论，各有利弊。各位请根据具体需求自行选择，但是配置文件内默认启用 DoT，因为目前国内没有封锁或管制。
#   DoH: 以 https:// 开头的 DNS 服务器。拥有更好的伪装性，且几乎不可能被运营商或网络管理封锁，但查询效率和安全性可能略低。
#   DoT: 以 tls:// 开头的 DNS 服务器。拥有更高的安全性和查询效率，但端口有可能被管制或封锁。
#   若要了解更多关于 DoH/DoT 相关技术，请自行查阅规范文档。

# 代理组
# 下面这3个不要引到订阅里去 要不会出错
# Will be ignored after profile selection
#proxies:
#  - name: Shadowsocks
#    type: socks5
#    server: 127.0.0.1
#    port: 1080
#proxy-groups:
#  - name: Proxy
#    type: select
#    proxies:
#      - Shadowsocks
#rules:
#  - 'MATCH,DIRECT'

# Clash for Windows
# Proxies module latency test settings
cfw-latency-timeout: 3000
cfw-latency-url: http://edge.microsoft.com/captiveportal/generate_204

# 混合配置（mixin）
# 支持向所有配置文件中注入公共属性设置
#cfw-profile-mixin:
  #dns:
    #enable: true
    #listen: :53
    #enhanced-mode: fake-ip
    #nameserver:
     #- 223.5.5.5 # 阿里DNS
     #- 180.76.76.76 # 百度DNS
     #- 119.29.29.29 # 腾讯DNS
     #- 117.50.11.11 # ONE DNS拦截版 恶意网站拦截、广告过滤
     #- 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
     #- 114.114.114.114 # 114DNS
  #experimental:
    #interface-name: WLAN

#自定义配置目录
#cfw-profiles-path: 'C:\Users\Administrator\.config\clash\profiles'

# 打断连接
# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
#cfw-conn-break-strategy:
#  proxy: chain # none/chain/all
#  profile: true # true/false
#  mode: true # true/false
cfw-conn-break-strategy:
  proxy: chain
  profile: true
  mode: true

# 自定义状态栏图标
#cfw-tray-icon:
#default: .\resources\static\imgs\logo_64.png        # 默认图标
#system-proxy-on: .\resources\static\imgs\custom.ico   # 开启系统代理后图标

# 自定义字体
#cfw-font-family: "Noto Sans TC"   # 系统中存在的字体

# 自定义请求头
#cfw-http-headers:
  #token: "123456"
  #cfw-version: "0.9.11"

# 自定义节点排序
# 可选参数：
#  default：按配置文件定义节点顺序
#  latency：按节点延迟升序排列
#  alphabet：按节点名称字母表排列
# Sort proxies in Proxies module by default/latency/alphabet
cfw-proxies-order: default

# 子进程 启动其他应用
# Run child process after CFW started
# Refer: https://docs.cfw.lbyczf.com/contents/childprocess.html
#cfw-child-process:
  # 启动订阅转换程序，端口号7893
  #- command: "subconverter.exe" # run.cmd 程序名称 subconverter.exe -cfw >>logs/run.log 2>&1
    #args:
      #- "-cfw" # 运行参数1
      #- "-f" # 运行参数2
      #- "pref-acl4ssr.yml" # 运行参数3
    #options:
      #cwd: subconverter # 子进程工作目录
      #detached: true # 子进程独立于其父进程运行
      #shell: true # 则在 shell 中运行 command
      #windowsHide: true # 隐藏子进程的控制台窗口
  # 启动网易云，端口号3333
  #- command: "unblockneteasemusic.exe" # 启动网易云
    #args:
      #- "-p" # 运行参数1
      #- "3333" # 运行参数2
    #options:
      #cwd: unblockNeteaseMusic # 子进程工作目录
      #detached: true # 子进程独立于其父进程运行
      #shell: true # 则在 shell 中运行 command
      #windowsHide: true # 隐藏子进程的控制台窗口

# 系统代理跳过列表 cfw-bypass
# System proxy will ignore these domains(or ipnet)
# 系统代理跳过列表-备份的，不起作用，
# 使用时可以将cfw-bypass-bak与cfw-bypass内容互换
#cfw-bypass-bak:
# 原有字段不用删除
# 系统代理跳过列表 起作用的
#cfw-bypass:
